# HTCondor Submit File for Batched Preprocessing

executable = /home/hep/jcc525/gan_particle_physics/condor/merge_script.sh
arguments = --pdg 13 --monitor-id 4

initialdir = /home/hep/jcc525/gan_particle_physics/condor

output = logs/merge_batch_$(ClusterId).$(Process).out
error = logs/merge_batch_$(ClusterId).$(Process).err
log = logs/merge_batch_$(ClusterId).$(Process).log

+MaxRuntime = 7200

request_memory = 32GB
request_disk = 40GB

queue 1