executable = /home/hep/jcc525/gan_particle_physics/condor/job_script.sh
arguments = --output-name bounded_r_neutron_2 --pdg 2112 --monitor-id 4 --gp 10 --entries 10000000 --test-entries 500000 --epochs 70 --device cuda --model wgan-gp --patience 35 --lr-g 2e-5 --lr-c 2e-5 --log-interval 1 --n-critic 5 --batch-size 1024 --latent-dim 128
initialdir = /home/hep/jcc525/gan_particle_physics/condor

output = logs/gan_$(ClusterId).$(ProcId).out
error = logs/gan_$(ClusterId).$(ProcId).err
log = logs/gan_$(ClusterId).$(ProcId).log

request_gpus = 1
request_cpus = 2
request_memory = 40GB
request_disk = 20GB

+MaxRuntime = 86400

queue 1