executable = /home/hep/jcc525/gan_particle_physics/condor/job_script.sh
arguments = --pdg 13 --monitor-id 4 --entries 50000 --epochs 50 --output-name gan_test_50k_50 --device cpu --model gan

initialdir = /home/hep/jcc525/gan_particle_physics/condor

output = logs/gan_$(ClusterId).$(ProcId).out
error = logs/gan_$(ClusterId).$(ProcId).err
log = logs/gan_$(ClusterId).$(ProcId).log

request_gpus = 0
request_cpus = 2
request_memory = 8GB
request_disk = 20GB

+MaxRuntime = 7200

queue 1